name = "cron-trigger_test"
type = "javascript"

account_id = ""
workers_dev = true
route = ""
zone_id = ""
compatibility_date = "2022-01-05"

[vars]
GITHUB_OWNER = "mygithubtest00"
GITHUB_REPO = "public_public_test"
GITHUB_WORKFLOW_FILE_NAME = "test.yml"
GITHUB_BRANCH = "master"

[triggers]
crons = ["* * * * *"]
# crons = []
