name: test

on:
  workflow_dispatch:
    inputs:
      trigger:
        description: start/stop/continue
        required: true
        default: start

jobs:
  test:
    runs-on: ubuntu-20.04
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}-${{ github.event.inputs.trigger }}
    steps:
      - name: Add mask
        run: |
          echo "::add-mask::${{ secrets.PRIVATE_REPOSITORY }}"
          echo "::add-mask::${{ secrets.PRIVATE_REPOSITORY_NAME }}"

      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MY_GITHUB_TOKEN }}
          submodules: recursive
          fetch-depth: 0

      - name: Add cron trigger
        if: ${{ github.event.inputs.trigger == 'start' }}
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'cron-trigger_test'
          secrets: |
            GITHUB_TOKEN
          preCommands: cp -f wrangler_start.toml wrangler.toml
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Checkout submodule
        if: ${{ github.event.inputs.trigger == 'continue' }}
        working-directory: ./public_private_test/workspace
        run: |
          git checkout master
          git log -1 --pretty=format:%h

      - name: Translate file
        if: ${{ github.event.inputs.trigger == 'continue' }}
        working-directory: ./public_private_test/workspace
        run: ./1_translate_file_for_github_actions.sh

      - name: Update translated file
        if: ${{ github.event.inputs.trigger == 'continue' && success() }}
        working-directory: ./public_private_test/workspace
        run: |
          git config user.email "sundaowen@gmail.com"
          git config user.name "Sun Daowen"
          git add -A
          if [ -z "$(git status --porcelain)" ]; then
            echo "No changes to commit"
          else
            git commit -m "Update translated file" -q
          fi
          git push

      - name: Check save data
        if: ${{ github.event.inputs.trigger == 'continue' && success() }}
        id: check_save_data
        continue-on-error: true
        working-directory: ./public_private_test/workspace
        run: ./2_check_save_data_for_github_actions.sh

      - run: |
          echo ${{ steps.check_save_data.outcome }}
          echo ${{ steps.check_save_data.conclusion }}

      - name: Delete cron trigger
        if: ${{ github.event.inputs.trigger == 'stop' || failure() || steps.check_save_data.outcome == 'success' }}
        uses: cloudflare/wrangler-action@1.3.0
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          workingDirectory: 'cron-trigger_test'
          secrets: |
            GITHUB_TOKEN
          preCommands: cp -f wrangler_stop.toml wrangler.toml
        env:
          GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
